const ACTIONS = {
  ADD_ITEM: "ADD_ITEM",
  DELETE_ITEM: "DELETE_ITEM",
  EDIT_IEM: "EDIT_IEM",
  SHOW_NOT: "SHOW_NOT",
  HIDE_NOT: "HIDE_NOT",
  CLOSE_EDIT: "CLOSE_EDIT",
};

export default ACTIONS;
